Repository dusk-network/phoenix-core, pull requests merged in 2020-10, with the labels that each got.

#18 Bump outdated dependencies
  Cargo.toml
Labels: area:conf&build, type:tech-debt

#15 Implement storage logic for Note
  Cargo.toml
  src/note.rs
  tests/note_test.rs
Labels: type:refactor

#21 Use as default Note's position `u64::MAX` instead of `0`
  src/convert.rs
  src/fee.rs
  src/note.rs
  tests/note_test.rs
Labels: type:refactor

#26 Return Note::serialised_size from Note.read
  src/note.rs
Labels: type:bug

#24 Update poseidon dep & bump crate
  Cargo.toml
  tests/note_test.rs
Labels: type:refactor

#28 Amend preimage
  src/note.rs
Labels: area:cryptography, type:refactor
